# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# More GitHub Actions for Azure: https://github.com/Azure/actions

name: Build and deploy Node.js app to Azure Web App - Levelup

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read #This is required for actions/checkout

    steps:
      - uses: actions/checkout@v4

      - name: Set up Node.js version
        uses: actions/setup-node@v3
        with:
          node-version: '20.x'

      - name: npm install, build, and test
        run: |
          npm ci --include=dev
          npm run build
        env:
          NODE_ENV: production

      - name: Zip artifacts for deployment
        run: zip -r node-app.zip .next node_modules package.json server.js next.config.ts .deployment .skipbuild

      - name: Upload artifact for deployment job
        uses: actions/upload-artifact@v4
        with:
          name: node-app
          path: node-app.zip
          retention-days: 1

  deploy:
    runs-on: ubuntu-latest
    needs: build
    permissions:
      id-token: write #This is required for requesting the JWT
      contents: read #This is required for actions/checkout

    steps:
      - name: Download artifact from build job
        uses: actions/download-artifact@v4
        with:
          name: node-app

      - name: Unzip artifact for deployment
        run: unzip node-app.zip
      
      - name: Login to Azure
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZUREAPPSERVICE_CLIENTID_38C4D13154A6434A990B712E0170CBF5 }}
          tenant-id: ${{ secrets.AZUREAPPSERVICE_TENANTID_A522D44745CF4D3A865EA93620F5E98D }}
          subscription-id: ${{ secrets.AZUREAPPSERVICE_SUBSCRIPTIONID_802679A6905E4A8E9F7CCFE85D407413 }}

      - name: 'Deploy to Azure Web App'
        id: deploy-to-webapp
        uses: azure/webapps-deploy@v3
        with:
          app-name: 'Levelup'
          slot-name: 'Production'
          package: .
          startup-command: 'npm start'
      
      - name: Delete artifact to save storage
        if: always()
        uses: geekyeggo/delete-artifact@v5
        with:
          name: node-app